"""modified register form

Revision ID: 9f435f2a80c5
Revises: 37b1aeed6fc0
Create Date: 2025-04-20 02:26:13.348225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f435f2a80c5'
down_revision = '37b1aeed6fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
