"""updated csrf token id

Revision ID: cf77dfefe231
Revises: 9f435f2a80c5
Create Date: 2025-04-20 17:43:38.286221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf77dfefe231'
down_revision = '9f435f2a80c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
